<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
      class ValidationError extends Error {
        constructor(message, field) {
          super(message);
          this.field = field;
        }
      }

      class MathUtil {
        static sum(...numbers) {
          if (numbers.length === 0) {
            throw new ValidationError(
              "Total parameter is greater than 0",
              "numbers"
            );
          }
          let total = 0;
          for (const number of numbers) {
            total += number;
          }
          return total;
        }
      }

      try {
        console.log(MathUtil.sum()); // This will throw an error
        console.log("Faqih"); // This will not be executed
      } catch (error) {
        if (error instanceof ValidationError) {
          console.error(
            `Validation Error: Error  in field: ${error.field} with message: ${error.message}`
          ); // This will catch the error and log it
        } else {
          console.error(`Error: ${error.message}`); // This will catch other errors
        }
      } finally {
        console.log("Finally block executed"); // This will always be executed
      }
      console.log("Maryam"); // This will be executed after the error is caught
    </script>
  </body>
</html>
